package com.danielsalas.danisalud.ui

object Localization {
    private val strings = mapOf(
        "ca" to mapOf(
            "last_blood_pressure" to "Última Tensió",
            "last_weight" to "Últim Pes",
            "no_blood_pressure" to "Encara no hi ha registres de tensió",
            "no_weight" to "Encara no hi ha registres de pes",
            "add_measurement" to "Afegir Mesura",
            "view_history" to "Veure Historial",
            "settings" to "Configuració",
            "back" to "Tornar",
            "blood_pressure_tab" to "Tensió Arterial",
            "weight_tab" to "Pes",
            "scan_ocr_weight" to "📸 Escanejar Pes (OCR)",
            "systolic" to "Sistòlica (Alta) mmHg",
            "diastolic" to "Diastòlica (Baixa) mmHg",
            "pulse" to "Pulsacions (bpm) (Opcional)",
            "pulse_short" to "Pols",
            "save_blood_pressure" to "Desar Tensió",
            "save_weight" to "Desar Pes",
            "weight_label" to "Pes (kg)",
            "medical_history" to "Historial Mèdic",
            "delete" to "Eliminar",
            "camera_permission_needed" to "Es necessita permís de càmera per utilitzar l'OCR.",
            "grant_permission" to "Concedir Permís",
            "point_camera" to "Apunta amb la càmera a la pantalla de l'aparell i prem Capturar",
            "capture" to "📸 Capturar",
            "fill_weight" to "Omplir Pes",
            "settings_title" to "Configuració",
            "user_name_label" to "Nom de l'usuari/ària",
            "language_label" to "Idioma",
            "theme_label" to "Mode de pantalla",
            "theme_system" to "Sistema",
            "theme_light" to "Clar",
            "theme_dark" to "Fosc"
        ),
        "eu" to mapOf(
            "last_blood_pressure" to "Azken Tentsioa",
            "last_weight" to "Azken Pisua",
            "no_blood_pressure" to "Oraindik ez dago tentsio erregistrorik",
            "no_weight" to "Oraindik ez dago pisu erregistrorik",
            "add_measurement" to "Neurketa Gehitu",
            "view_history" to "Historia Ikusi",
            "settings" to "Ezarpenak",
            "back" to "Atzera",
            "blood_pressure_tab" to "Tentsio Arteriala",
            "weight_tab" to "Pisua",
            "scan_ocr_weight" to "📸 Pisua Eskaneatu (OCR)",
            "systolic" to "Sistolikoa (Altuak) mmHg",
            "diastolic" to "Diastolikoa (Baxuak) mmHg",
            "pulse" to "Pultsazioak (bpm) (Aukerakoa)",
            "pulse_short" to "Pultsua",
            "save_blood_pressure" to "Tentsioa Gorde",
            "save_weight" to "Pisua Gorde",
            "weight_label" to "Pisua (kg)",
            "medical_history" to "Historia Medikoa",
            "delete" to "Ezabatu",
            "camera_permission_needed" to "Kamera baimena behar da OCR erabiltzeko.",
            "grant_permission" to "Baimena Eman",
            "point_camera" to "Kamerarekin pantailara apuntatu eta Sakatu Capturar",
            "capture" to "📸 Atera",
            "fill_weight" to "Pisua Bete",
            "settings_title" to "Ezarpenak",
            "user_name_label" to "Erabiltzailearen izena",
            "language_label" to "Hizkuntza",
            "theme_label" to "Pantaila modua",
            "theme_system" to "Sistema",
            "theme_light" to "Argia",
            "theme_dark" to "Iluna"
        ),
        "gl" to mapOf(
            "last_blood_pressure" to "Última Tensión",
            "last_weight" to "Último Peso",
            "no_blood_pressure" to "Aínda non hai rexistros de tensión",
            "no_weight" to "Aínda non hai rexistros de peso",
            "add_measurement" to "Engadir Medida",
            "view_history" to "Ver Historial",
            "settings" to "Configuración",
            "back" to "Volver",
            "blood_pressure_tab" to "Tensión Arterial",
            "weight_tab" to "Peso",
            "scan_ocr_weight" to "📸 Escanear Peso (OCR)",
            "systolic" to "Sistólica (Alta) mmHg",
            "diastolic" to "Diastólica (Baixa) mmHg",
            "pulse" to "Pulsacións (bpm) (Opcional)",
            "pulse_short" to "Pulsos",
            "save_blood_pressure" to "Gardar Tensión",
            "save_weight" to "Gardar Peso",
            "weight_label" to "Peso (kg)",
            "medical_history" to "Historial Médico",
            "delete" to "Eliminar",
            "camera_permission_needed" to "Necesítase permiso de cámara para usar o OCR.",
            "grant_permission" to "Conceder Permiso",
            "point_camera" to "Apunta coa cámara á pantalla do aparello e preme Capturar",
            "capture" to "📸 Capturar",
            "fill_weight" to "Encher Peso",
            "settings_title" to "Configuración",
            "user_name_label" to "Nome do usuario/a",
            "language_label" to "Idioma",
            "theme_label" to "Modo de pantalla",
            "theme_system" to "Sistema",
            "theme_light" to "Claro",
            "theme_dark" to "Escuro"
        ),
        "an" to mapOf(
            "last_blood_pressure" to "Última Tensión",
            "last_weight" to "Último Peso",
            "no_blood_pressure" to "Aínda no hay rexistros de tensión",
            "no_weight" to "Aínda no hay rexistros de peso",
            "add_measurement" to "Agregá Medida",
            "view_history" to "Ver Historial",
            "settings" to "Configuración",
            "back" to "Volver",
            "blood_pressure_tab" to "Tensión Arterial",
            "weight_tab" to "Peso",
            "scan_ocr_weight" to "📸 Escaniá Peso (OCR)",
            "systolic" to "Sistólica (Alta) mmHg",
            "diastolic" to "Diastólica (Baja) mmHg",
            "pulse" to "Pulsacións (bpm) (Opcional)",
            "pulse_short" to "Pulsos",
            "save_blood_pressure" to "Guardá Tensión",
            "save_weight" to "Guardá Peso",
            "weight_label" to "Peso (kg)",
            "medical_history" to "Historial Médico",
            "delete" to "Borrá",
            "camera_permission_needed" to "Se necesita permíso de cámara pa usá o OCR.",
            "grant_permission" to "Dá Permíso",
            "point_camera" to "Apunta con a cámara pa la pantalla y primi Capturar",
            "capture" to "📸 Capturá",
            "fill_weight" to "Enchí Peso",
            "settings_title" to "Configuración",
            "user_name_label" to "Nombre d'o presonache",
            "language_label" to "Llingua",
            "theme_label" to "Modo pantalla",
            "theme_system" to "Sistema",
            "theme_light" to "Claro",
            "theme_dark" to "Escuro"
        ),
        "en" to mapOf(
            "last_blood_pressure" to "Latest Blood Pressure",
            "last_weight" to "Latest Weight",
            "no_blood_pressure" to "No blood pressure records yet",
            "no_weight" to "No weight records yet",
            "add_measurement" to "Add Measurement",
            "view_history" to "View History",
            "settings" to "Settings",
            "back" to "Back",
            "blood_pressure_tab" to "Blood Pressure",
            "weight_tab" to "Weight",
            "scan_ocr_weight" to "📸 Scan Weight (OCR)",
            "systolic" to "Systolic (High) mmHg",
            "diastolic" to "Diastolic (Low) mmHg",
            "pulse" to "Pulse (bpm) (Optional)",
            "pulse_short" to "Pulse",
            "save_blood_pressure" to "Save Blood Pressure",
            "save_weight" to "Save Weight",
            "weight_label" to "Weight (kg)",
            "medical_history" to "Medical History",
            "delete" to "Delete",
            "camera_permission_needed" to "Camera permission is required to use OCR.",
            "grant_permission" to "Grant Permission",
            "point_camera" to "Point camera at device screen and tap Capture",
            "capture" to "📸 Capture",
            "fill_weight" to "Fill Weight",
            "settings_title" to "Settings",
            "user_name_label" to "User Name",
            "language_label" to "Language",
            "theme_label" to "Screen Mode",
            "theme_system" to "System",
            "theme_light" to "Light",
            "theme_dark" to "Dark"
        ),
        "fr" to mapOf(
            "last_blood_pressure" to "Dernière Tension",
            "last_weight" to "Dernier Poids",
            "no_blood_pressure" to "Aucun enregistrement de tension",
            "no_weight" to "Aucun enregistrement de poids",
            "add_measurement" to "Ajouter Mesure",
            "view_history" to "Voir l'Historique",
            "settings" to "Paramètres",
            "back" to "Retour",
            "blood_pressure_tab" to "Tension Artérielle",
            "weight_tab" to "Poids",
            "scan_ocr_weight" to "📸 Scanner Poids (OCR)",
            "systolic" to "Systolique (Haut) mmHg",
            "diastolic" to "Diastolique (Bas) mmHg",
            "pulse" to "Pouls (bpm) (Optionnel)",
            "pulse_short" to "Pouls",
            "save_blood_pressure" to "Enregistrer Tension",
            "save_weight" to "Enregistrer Poids",
            "weight_label" to "Poids (kg)",
            "medical_history" to "Historique Médical",
            "delete" to "Supprimer",
            "camera_permission_needed" to "Permission de caméra requise pour l'OCR.",
            "grant_permission" to "Accorder la permission",
            "point_camera" to "Pointez la caméra sur l'écran et appuyez sur Capturer",
            "capture" to "📸 Capturer",
            "fill_weight" to "Remplir Poids",
            "settings_title" to "Paramètres",
            "user_name_label" to "Nom de l'utilisateur",
            "language_label" to "Langue",
            "theme_label" to "Mode d'affichage",
            "theme_system" to "Système",
            "theme_light" to "Clair",
            "theme_dark" to "Sombre"
        ),
        "de" to mapOf(
            "last_blood_pressure" to "Letzter Blutdruck",
            "last_weight" to "Letztes Gewicht",
            "no_blood_pressure" to "Noch keine Blutdruckdaten",
            "no_weight" to "Noch keine Gewichtsdaten",
            "add_measurement" to "Messung Hinzufügen",
            "view_history" to "Verlauf Anzeigen",
            "settings" to "Einstellungen",
            "back" to "Zurück",
            "blood_pressure_tab" to "Blutdruck",
            "weight_tab" to "Gewicht",
            "scan_ocr_weight" to "📸 Gewicht Scannen (OCR)",
            "systolic" to "Systolisch (Hoch) mmHg",
            "diastolic" to "Diastolisch (Tief) mmHg",
            "pulse" to "Puls (bpm) (Optional)",
            "pulse_short" to "Puls",
            "save_blood_pressure" to "Blutdruck Speichern",
            "save_weight" to "Gewicht Speichern",
            "weight_label" to "Gewicht (kg)",
            "medical_history" to "Medizinischer Verlauf",
            "delete" to "Löschen",
            "camera_permission_needed" to "Kameraberechtigung für OCR erforderlich.",
            "grant_permission" to "Berechtigung erteilen",
            "point_camera" to "Kamera auf das Display richten und Aufnehmen",
            "capture" to "📸 Aufnehmen",
            "fill_weight" to "Gewicht Ausfüllen",
            "settings_title" to "Einstellungen",
            "user_name_label" to "Benutzername",
            "language_label" to "Sprache",
            "theme_label" to "Anzeigemodus",
            "theme_system" to "System",
            "theme_light" to "Hell",
            "theme_dark" to "Dunkel"
        ),
        "zh" to mapOf(
            "last_blood_pressure" to "最新血压",
            "last_weight" to "最新体重",
            "no_blood_pressure" to "暂无血压记录",
            "no_weight" to "暂无体重记录",
            "add_measurement" to "添加测量",
            "view_history" to "查看历史",
            "settings" to "设置",
            "back" to "返回",
            "blood_pressure_tab" to "血压",
            "weight_tab" to "体重",
            "scan_ocr_weight" to "📸 扫描体重 (OCR)",
            "systolic" to "收缩压 (高) mmHg",
            "diastolic" to "舒张压 (低) mmHg",
            "pulse" to "脉搏 (bpm) (可选)",
            "pulse_short" to "脉搏",
            "save_blood_pressure" to "保存血压",
            "save_weight" to "保存体重",
            "weight_label" to "体重 (kg)",
            "medical_history" to "医疗历史",
            "delete" to "删除",
            "camera_permission_needed" to "使用OCR需要相机权限。",
            "grant_permission" to "授予权限",
            "point_camera" to "将相机对准设备屏幕并点击捕获",
            "capture" to "📸 捕获",
            "fill_weight" to "填写体重",
            "settings_title" to "设置",
            "user_name_label" to "用户名",
            "language_label" to "语言",
            "theme_label" to "屏幕模式",
            "theme_system" to "系统",
            "theme_light" to "浅色",
            "theme_dark" to "深色"
        ),
        "ko" to mapOf(
            "last_blood_pressure" to "최근 혈압",
            "last_weight" to "최근 체중",
            "no_blood_pressure" to "혈압 기록이 없습니다",
            "no_weight" to "체중 기록이 없습니다",
            "add_measurement" to "측정값 추가",
            "view_history" to "기록 보기",
            "settings" to "설정",
            "back" to "뒤로",
            "blood_pressure_tab" to "혈압",
            "weight_tab" to "체중",
            "scan_ocr_weight" to "📸 체중 스캔 (OCR)",
            "systolic" to "수축기 (고) mmHg",
            "diastolic" to "이완기 (저) mmHg",
            "pulse" to "맥박 (bpm) (선택사항)",
            "pulse_short" to "맥박",
            "save_blood_pressure" to "혈압 저장",
            "save_weight" to "체중 저장",
            "weight_label" to "체중 (kg)",
            "medical_history" to "의료 기록",
            "delete" to "삭제",
            "camera_permission_needed" to "OCR을 사용하려면 카메라 권한이 필요합니다.",
            "grant_permission" to "권한 허용",
            "point_camera" to "장치 화면에 카메라를 대고 캡처를 누르세요",
            "capture" to "📸 캡처",
            "fill_weight" to "체중 채우기",
            "settings_title" to "설정",
            "user_name_label" to "사용자 이름",
            "language_label" to "언어",
            "theme_label" to "화면 모드",
            "theme_system" to "시스템",
            "theme_light" to "라이트",
            "theme_dark" to "다크"
        ),
        "es-la" to mapOf(
            "last_blood_pressure" to "Última Tensión",
            "last_weight" to "Último Peso",
            "no_blood_pressure" to "Aún no hay registros de presión",
            "no_weight" to "Aún no hay registros de peso",
            "add_measurement" to "Agregar Medición",
            "view_history" to "Ver Historial",
            "settings" to "Configuración",
            "back" to "Volver",
            "blood_pressure_tab" to "Presión Arterial",
            "weight_tab" to "Peso",
            "scan_ocr_weight" to "📸 Escanear Peso (OCR)",
            "systolic" to "Sistólica (Alta) mmHg",
            "diastolic" to "Diastólica (Baja) mmHg",
            "pulse" to "Pulso (bpm) (Opcional)",
            "pulse_short" to "Pulso",
            "save_blood_pressure" to "Guardar Presión",
            "save_weight" to "Guardar Peso",
            "weight_label" to "Peso (kg)",
            "medical_history" to "Historial Médico",
            "delete" to "Eliminar",
            "camera_permission_needed" to "Se necesita permiso de cámara para usar el OCR.",
            "grant_permission" to "Conceder Permiso",
            "point_camera" to "Apunta con la cámara a la pantalla del aparato y presiona Capturar",
            "capture" to "📸 Capturar",
            "fill_weight" to "Rellenar Peso",
            "settings_title" to "Configuración",
            "user_name_label" to "Nombre de usuario/a",
            "language_label" to "Idioma",
            "theme_label" to "Modo de pantalla",
            "theme_system" to "Sistema",
            "theme_light" to "Claro",
            "theme_dark" to "Oscuro"
        )
    )

    fun get(lang: String, key: String): String {
        val langMap = strings[lang] ?: strings["ca"] ?: return key
        return langMap[key] ?: strings["ca"]?.get(key) ?: key
    }
}
